# Create a GitHub release and publish to Pypi.
#
# This action does the following:
#
# 1. Bump version.
#    This creates a new PR and merges it.
# 2. Create release in GitHub.
# 3. Publish to Pypi.
#
# At this point, does not add assets to the release.
# Use the `build-asset` action.
name: Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version to bump'
        required: true
        type: choice
        options:
          - Major
          - Minor
          - Patch
      create_release:
        description: 'Create release in GitHub'
        required: true
        default: Yes
        type: choice
        options:
          - Yes
          - No
      publish:
        description: 'Publish to Pypi'
        required: true
        default: Yes
        type: choice
        options:
          - Yes
          - No

permissions:
  contents: write
  actions: read

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Bump version
