name: tests

on:
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Min and max versions supported
        python-version: ['3.10', '3.11']
    name: Python ${{ matrix.python-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install libEGL
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -y libegl1-mesa
        if: runner.os == 'Linux'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install requirements
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements-dev.txt
      - name: Run tests
        # Test folder(s) configured in `pyproject.toml`
        run: |
          python -m pytest .
